# H2 database configs
spring.datasource.url=jdbc:h2:file:~/goodreads/src/main/resources/goodreads
spring.datasource.username=
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.sql.init.mode=never

# Redis configs (for local host)
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
